package com.candela.forte.integration.db.config;

public enum ForteConstants {

	CUSTOMER_DETAILS_UPDATED_SMS("CUSTOMER_DETAILS_UPDATED_SMS"),
	SMS_SERVER_USER_ID("SMS_SERVER_USER_ID"),
	SMS_SERVER_KEY("SMS_SERVER_KEY"),
	SMS_HEADER("SMS_HEADER"),
	SMS_MAX_RECORDS("SMS_MAX_RECORDS"),
	FIRST_RECHARGE_SMS_EN("FIRST_RECHARGE_SMS_EN"),
	FIRST_RECHARGE_SMS_LAO("FIRST_RECHARGE_SMS_LAO"),
	RECHARGE_SMS_NO_CUSTOMER_DETAILS_LAO("RECHARGE_SMS_NO_CUSTOMER_DETAILS_LAO"),
	RECHARGE_SMS_NO_CUSTOMER_DETAILS_EN("RECHARGE_SMS_NO_CUSTOMER_DETAILS_EN"),
	
	RECHARGE_SMS_CUSTOMER_DETAILS_LAO("RECHARGE_SMS_CUSTOMER_DETAILS_LAO"),
	RECHARGE_SMS_CUSTOMER_DETAILS_EN("RECHARGE_SMS_CUSTOMER_DETAILS_EN"),
	
	FIRST_DAY_OF_EVERY_MONTH_EN("FIRST_DAY_OF_EVERY_MONTH_EN"),
	FIRST_DAY_OF_EVERY_MONTH_LAO("FIRST_DAY_OF_EVERY_MONTH_LAO"),
	LANGUAGE_LAO("LA"),
	FIRST_REMINDER_SMS_EN("FIRST_REMINDER_SMS_EN"),
	FIRST_REMINDER_SMS_LAO("FIRST_REMINDER_SMS_LAO"),
	SECOND_REMINDER_SMS_LAO("SECOND_REMINDER_SMS_LAO"),
	SECOND_REMINDER_SMS_EN("SECOND_REMINDER_SMS_EN"),
	SMS_SUCCESS_CODE("20"),
	MAX_PREMIUN_AMOUNT("MAX_PREMIUN_AMOUNT"),
	CUSTOMER_CARE_PROCESS_REST_URL("CUSTOMER_CARE_PROCESS_REST_URL"),
	FIRST_SMS_REMINDER_DAYS("FIRST_SMS_REMINDER_DAYS"),
	SECOND_SMS_REMINDER_DAYS("SECOND_SMS_REMINDER_DAYS"),THIRD_REMINDER_DAYS("THIRD_REMINDER_DAYS"),
	SMS_WSDL_URL("SMS_WSDL_URL"),SMS_WSDL_QNAME("SMS_WSDL_QNAME");
	
	private String value;
	
	public String getValue() {
		return this.value;
	}
	
	private ForteConstants(String value) {
		this.value=value;
	}

}
